### ISSUE TITLE
Can it parse HTML string directly instead URL?

### ISSUE THREAD

**Issue by vickyRathee** [blakeembrey/node-htmlmetaparser#24]
Any way to parse HTML directly instead the URL? something like ...

```
const html= "html here";

const handler = new Handler(
  (err, result) => {
    console.log(result);
  },
  {
    html
  }
);

// Create a HTML parser with the handler.
const parser = new Parser(handler, { decodeEntities: true });
parser.write(html);
parser.done();
```

**Comment by blakeembrey** [comment]
That's literally the example in the README.

**Comment by blakeembrey** [comment]
Here's a working demo link from the README you can adapt your needs: https://runkit.com/blakeembrey/htmlmetaparser. Feel free to send a PR to clarify the README documentation where needed.
