### ISSUE TITLE
resolveUrl throws on bad urls

### ISSUE THREAD

**Issue by jonathonhawkins92** [blakeembrey/node-htmlmetaparser#33]
I bumped head first into this edge case from: [busterandpunch](https://www.busterandpunch.com/shop/electricity/dimmer-switches/1g-dimmer-smoked-bronze/)

```
<a href="https://" class="expanded">Trade</a>
```

This throws and doesn't seem to be caught by the error handler, a simple solution is to just try catch the `resolveUrl`, and return `undefined`, though in some places it would mean opting out of creating entries, thoughts?

**Comment by blakeembrey** [comment]
Closed with https://github.com/blakeembrey/node-htmlmetaparser/pull/34.

**Comment by blakeembrey** [comment]
> though in some places it would mean opting out of creating entries, thoughts?

Seems reasonable to skip them to me, thanks!
